# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

# queue:
#   name: Hosted
#   demands: npm
#  
steps:
- task: NodeTool@0
  displayName: 'Use Node 8.x'
  inputs:
    versionSpec: 8.x
  
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core 2.1'
  inputs:
    version: 2.1.402
  
- task: Npm@1
  displayName: 'Install Azure Functions Core Tools'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g azure-functions-core-tools'
  
- bash: 'func extensions install'
  #workingDirectory: .
  displayName: 'Install extensions'
 
- task: Npm@1
  displayName: 'npm install'
  inputs:
    #workingDir: .
    verbose: false
  
- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    #workingDir: .
    verbose: false
    customCommand: 'run-script test'
  
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    #rootFolderOrFile: .
    includeRootFolder: false
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop' 